### ISSUE TITLE
"Allow Tearing" on the OLED Deck restricts GPU clocks to 200/400/1040MHz, greatly downgrading performance

### ISSUE THREAD

**Issue by v1ld** [ValveSoftware/SteamOS#1223]
If you enable "Allow Tearing" in a graphically intensive game like CP 2077 or BG3, or even good old The Witcher 3, GPU clocks oscillate between 200/400/1040MHz for me.  This halves fps in CP 2077/BG3 with my settings.

This only became an issue on the OLED Deck.  I had the same settings on the LCD deck running the same 3.5.x code from Preview and now Stable and did not see any such issues there.

Original reply to the other, long thread follows.  Posting this separately since whatever else may be causing issues for folks in that thread, this is a reproducible issue for me with a workaround that hopefully makes it easier to identify the cause.

Disabling "Allow Tearing" in the Performance tab completely solves the problem for me.  The GPU will still clock to 200/400/1040MHz when it can meet the fps target while doing so - this is a good thing!  But the problem I was seeing where it would oscillate between 200/400/1040MHz values and no other, greatly dropping fps as shown in MangoHUD (and visibly!) is no longer a problem with Allow Tearing disabled.

I was seeing the 220/1040 problem in games like CP 2077, BG3, TW3 on this new OLED deck where I never saw it on the LCD deck running the same 3.5.x branch - I was on Preview on the LCD.  I noticed the problem would fix itself if I brought up the ... right panel - the game's performance would visibly improve and MangoHUD would show GPU clock going to 1600MHz and values below as needed.

Guessing that the panel enables vsync I tried disabling Allow Tearing and the problem immediately goes away.  

Is there something different about how vsync is being handled on the OLED that could be causing this?

In the meantime, performance is back and I can live with vsync.

_Originally posted by @v1ld in https://github.com/ValveSoftware/SteamOS/issues/1176#issuecomment-1823479765_

**Comment by waspennator** [comment]
According to other users on the thread, turning off allow tearing doesn't fix the performance

**Comment by lostgoat** [comment]
Hey @v1ld 

Thanks for the detailed report. There is a temporary workaround for this in the latest preview channel update (3.5.6).

Just to clarify though. The GPU clocks are not the issue here. The problem is that due to a bug the GPU isn't being fed commands fast enough, so it goes back down to an idle state (as it should).

In most cases seeing the GPU oscillate between 200/400/1040MHz values is normal. But if performance is not meeting expectations there is a bug elsewhere that is preventing the game from utilizing the HW at its full potential. So getting reports like these with game examples and perf differences is exactly what we need.

**Comment by v1ld** [comment]
@lostgoat I've updated to the latest Preview channel release and can confirm in no longer seeing the problem.  I've tried CP 2077, BG3, TW3, MH World - none of them show fps drops while carried at 1040MHz like earlier. Allow Tearing makes no difference anymore.

Thanks for the quick rollout of a workaround.
