### ISSUE TITLE
Audio jack not working in windows after dual boot process

### ISSUE THREAD

**Issue by DiegoPeter** [ValveSoftware/SteamOS#126]
I Dual Booted SteamOS and Windows using the same procedures that directhex uses with Ye Olde SteamOSe but after booting into windows i can't seem to hear anything with my headphone.I uninstalled SteamOS and fixed windows boot and the audio simply works now.

**Comment by ProfessorKaos64** [comment]
@DiegoPeter please recheck this and close if it no longer affects you. In desktop mode, open a terminal window and check the output of lsb_release -a. Ensure you are on brewmaster, as Alchemist is no longer supported. You must do a full reinstall to move to brewmaster at this time. See the wiki for details.

This was an issue a while back in the Steam beta client, but has since been largely fixed, at least on Nvidia hardware.
