### ISSUE TITLE
System page says I'm on 3.4.11 but I can use 3.5 features

### ISSUE THREAD

**Issue by fsworld009** [ValveSoftware/SteamOS#1323]
#### Your system information

* Steam client version: 1702079146
* SteamOS version: Not sure
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

I noticed that in the Settings -> system page it says I'm on 3.4.11

However, I can use the new display setting and HDR setting mentioned in the 3.5 [preview notes](https://store.steampowered.com/news/app/1675200/view/3686804163591367815), and `distrobox` is already installed (I'm sure I didn't manually install it). Manually click check for updates also doesn't prompt any update for me.

I also tried switched to Beta then switched back, that also didn't work

So it looks like 3.5 is actually installed but somehow 3.4.11 is still the reported version. Has anyone been in similar situation? Is there anyway to fix it?

#### Steps for reproducing this issue:

Not sure how I got into this situation, don't really have any reproducable step in mind.

**Comment by lostgoat** [comment]
Most likely `/etc/os-release` was edited on your system and it ended up on the overlayfs. 

I’m away from a pc so I don’t remember what is the full path to the overlayfs, but deleting the file from there will probably fix the visual bug.

The bug is most likely purely visual, no need to worry about it.

if you generate a system report and read through it you’ll most likely find a list of files that are edited in the overlayfs.

**Comment by kisak-valve** [comment]
Most likely `/var/lib/overlays/etc/upper/os-release`.

**Comment by fsworld009** [comment]
@kisak-valve @lostgoat thanks for your help! I removed `/var/lib/overlays/etc/upper/os-release` and rebooted, the reported version is now correct (3.5.7).
