### ISSUE TITLE
(SteamOS 3.6/3.7) unable to mount any external storage devices.

### ISSUE THREAD

**Issue by deathblade201243** [ValveSoftware/SteamOS#1646]
#### Your system information

* Steam client version:1726683985
* SteamOS version: 3.6.13 and 3.7
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When I try to mount any external storage device regardless if its a USB or Hard Drive and regardless of its format it just fails with the message "Could not mount this device". it doesn't even seem to try to mount it just instantly fails and if I look in KDE Partition manager the formats are unknown. these same devices work fine on 3.5. Microsd mounting works fine though.

#### Steps for reproducing this issue:

1.  load up either Nested Desktop or Desktop Mode.
2.  insert a storage device either directly through the charging port or with a dock.
3.  try to mount the device.

**Comment by bertogg** [comment]
Please try this:

1. Reboot the device completely
2. Go to desktop mode and open a terminal (or log in via ssh if you prefer)
3. Insert the USB hard drive
4. Type this in the terminal and paste the output here:
```
sudo lsblk -d /dev/sd*

sudo blkid /dev/sd*

sudo journalctl -b | grep -E 'kernel:.*sd[a-z]|block-device-event'
```

**Comment by deathblade201243** [comment]
```
Sep 20 10:33:41 steamdeck kernel: sd 0:0:0:0: [sda] Media removed, stopped polling
Sep 20 10:33:41 steamdeck kernel: sd 0:0:0:0: [sda] Attached SCSI removable disk
Sep 20 10:33:41 steamdeck kernel: sd 0:0:0:1: [sdb] 384503808 512-byte logical blocks: (197 GB/183 GiB)
Sep 20 10:33:41 steamdeck kernel: sd 0:0:0:1: [sdb] Write Protect is off
Sep 20 10:33:41 steamdeck kernel: sd 0:0:0:1: [sdb] Mode Sense: 21 00 00 00
Sep 20 10:33:41 steamdeck kernel: sd 0:0:0:1: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Sep 20 10:33:41 steamdeck kernel: sd 0:0:0:1: [sdb] Attached SCSI removable disk
Sep 20 10:33:41 steamdeck systemd[1]: Started /usr/lib/hwsupport/block-device-event.sh add sdb.
Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: Mounting volume... OK
Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: Processing of $MFT and $MFTMirr completed successfully.
Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: Checking the alternate boot sector... OK
Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: NTFS volume version is 3.1.
Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: NTFS partition /dev/sdb was processed successfully.
Sep 20 10:33:42 steamdeck block-device-event.sh[53266]: Error running call Mount on /dev/sdb (status = 1)
Sep 20 10:33:44 steamdeck kernel: ntfs3: sdb: It is recommened to use chkdsk.
Sep 20 10:33:44 steamdeck kernel: ntfs3: sdb: volume is dirty and "force" flag is not set!
```

I can see its stating it is "dirty" which I know  in Linux can cause a device not to mount. thing is even after I do run a repair not only does it not find any errors but it also shows as "dirty" again after it fails to mount.

**Comment by bertogg** [comment]
> ```
> Sep 20 10:33:41 steamdeck systemd[1]: Started /usr/lib/hwsupport/block-device-event.sh add sdb.
> Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: Mounting volume... OK
> Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: Processing of $MFT and $MFTMirr completed successfully.
> Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: Checking the alternate boot sector... OK
> Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: NTFS volume version is 3.1.
> Sep 20 10:33:41 steamdeck block-device-event.sh[53264]: NTFS partition /dev/sdb was processed successfully.
> Sep 20 10:33:42 steamdeck block-device-event.sh[53266]: Error running call Mount on /dev/sdb (status = 1)
> ```

1. It seems that the external drive does not have a partition table (the filesystem is directly on /dev/sdb and not /dev/sdb1). This is probably confusing the KDE Partition Manager.

2. I don't see the output of `sudo lsblk -d /dev/sd*` or `sudo blkid /dev/sd*`, which can probably confirm what I said in point 1.

3. The external drive has an NTFS filesystem, but SteamOS only supports and auto-mounts ext4 (NTFS should work if you mount it manually from the destkop mode, for non-Steam games).

4. It looks like you have installed some third-party tool or modification to make SteamOS auto-mount ntfs, can you confirm this? Otherwise the system should not try to mount an NTFS drive automatically.

**Comment by deathblade201243** [comment]
I use https://gitlab.com/popsulfr/steamos-btrfs in order to automount my BTRFS MicroSD but I've tried without it installed and still have the same issue. the Hard Drive works perfectly fine when I downgrade to 3.5 so It cant be an issue with the Hard Drive itself. its only an issue on 3.6 and 3.7.

**Comment by lostgoat** [comment]
@deathblade201243 your drive is working properly. It just won’t automatically automount because NTFS is not a supported file system format for steam games/proton.

If your drive contains steam games, then you should reformat your drive to a file system that is compatible with SteamOS, e.g. ext4. Trying to launch steam or proton games from an NTFS drive can lead to all sorts of subtle bugs, which is why it’s unsupported.

If your drive contains content that is unrelated to steam/proton, then you can configure your drive to automount via the desktop mode disk management utilities.

**Comment by deathblade201243** [comment]
> @deathblade201243 your drive is working properly. It just won’t automatically automount because NTFS is not a supported file system format for steam games/proton.


I am not trying to automount it I just want to mount it at all. it works perfectly fine on 3.5 but will not mount at all  on 3.6 or 3.7. i am trying to mount two drives one which is a 200GB microSD using this https://www.amazon.com/Anker-Reader-Memory-RS-MMC-Micro/dp/B07NW8RPYN which I use as a means to easily transfer files between windows and linux. the other one is a 2TB hard drive. both of them work on 3.5. as far as Steam games running off an NTFS is concerned I tested it plenty on 3.5 without any issues. there is something wrong with 3.6 and 3.7 which prevents them from mounting

**Comment by deathblade201243** [comment]
> > @deathblade201243 your drive is working properly. It just won’t automatically automount because NTFS is not a supported file system format for steam games/proton.
> 
> I am not trying to automount it I just want to mount it at all. it works perfectly fine on 3.5 but will not mount at all on 3.6 or 3.7. i am trying to mount two drives one which is a 200GB microSD using this https://www.amazon.com/Anker-Reader-Memory-RS-MMC-Micro/dp/B07NW8RPYN which I use as a means to easily transfer files between windows and linux. the other one is a 2TB hard drive. both of them work on 3.5. as far as Steam games running off an NTFS is concerned I tested it plenty on 3.5 without any issues. there is something wrong with 3.6 and 3.7 which prevents them from mounting regardless if its an automount or manually.

**Comment by bertogg** [comment]
Hi @deathblade201243, I can confirm that plain SteamOS 3.6 (without `steamos-btrfs` or anything else) can mount NTFS drives just fine if you do it manually from the command line or from the desktop mode.

Then I tried this `steamos-btrfs` tool with SteamOS 3.6 and I can see why this is failing (you can run `journalctl` to see if you have the same error):

```
busctl[2935]: Call failed: Mount option `uid=1000' is not allowed
```

Since this is a third-party tool I think that you should open an issue there, `steamos-btrfs` is making non-trivial changes to the base system:

https://gitlab.com/popsulfr/steamos-btrfs/-/raw/v1.3.2.20240706/files/usr/lib/hwsupport/steamos-automount.sh.patch.old.20240220124315.20240216.1000

**Comment by deathblade201243** [comment]
> Hi @deathblade201243, I can confirm that plain SteamOS 3.6 (without `steamos-btrfs` or anything else) can mount NTFS drives just fine if you do it manually from the command line or from the desktop mode.
> 
> Then I tried this `steamos-btrfs` tool with SteamOS 3.6 and I can see why this is failing (you can run `journalctl` to see if you have the same error):
> 
> ```
> busctl[2935]: Call failed: Mount option `uid=1000' is not allowed
> ```
> 
> Since this is a third-party tool I think that you should open an issue there, `steamos-btrfs` is making non-trivial changes to the base system:
> 
> https://gitlab.com/popsulfr/steamos-btrfs/-/raw/v1.3.2.20240706/files/usr/lib/hwsupport/steamos-automount.sh.patch.old.20240220124315.20240216.1000

Yeah this is indeed the correct answer. I had thought I removed it with "Reinstall SteamOS" but there must have been remnants leftover that only a complete reimage could remove. it is now working after the reimage though.
