### ISSUE TITLE
SteamOS + TV +Sound via HDMI = No sound.

### ISSUE THREAD

**Issue by DiWorm** [ValveSoftware/SteamOS#171]
Hello!

I install SteamOS and have some problems:
HDMI cable v1.4
TV see audio from HDMI 
PC use HDMI audio output in config.
But i see only picture, no audio.. I trying play with auido setting, but no effect to me. All good work with Win7+TV.
I also trying to off integ. audio card in BIOS.
Also - cant use steam bug reporter coz "Not autorized 401 error"

UPD: Oh, yeah, my pc config:
i3
4 gb ram
Palit GTX 240
TV - Philips 4 series.

**Comment by ProfessorKaos64** [comment]
please recheck this and close if it no longer affects you. In desktop mode, open a terminal window and check the output of `lsb_release -a`. Ensure you are on brewmaster, as Alchemist is no longer supported. You must do a full reinstall to move to brewmaster at this time. See the [wiki](https://github.com/ValveSoftware/SteamOS/wiki) for details.

This was an issue a while back in the Steam beta client, but has since been largely fixed, at least on Nvidia hardware.
