### ISSUE TITLE
System>Manage Printing does not open the CUPS administration webpage

### ISSUE THREAD

**Issue by Sunspark-007** [ValveSoftware/SteamOS#1719]
#### Your system information

* Steam client version: 1730853027
* SteamOS version: 3.6.20
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I figured I would see an administration webpage for CUPS.

What I see instead is:

"Unable to connect
Firefox can’t establish a connection to the server at localhost:631.
The site could be temporarily unavailable or too busy. Try again in a few moments.
If you are unable to load any pages, check your computer’s network connection.
If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web."

#### Steps for reproducing this issue:

1. In desktop mode start menu, System>Manage Printing

**Comment by bertogg** [comment]
Hi!

The CUPS server is started on demand when someone tries to use the printing socket.

That means that if you try to open the administration web page on your browser after boot it won't work because CUPS is down.

What you can do is simply open the browser's Print dialog and close it immediately. Opening the print dialog (or running `lpq` from the command line) is enough to start the CUPS server. After that you should be able to open the administration page normally.

I agree it's a minor annoyance but it's trivial to fix and the administration web page is almost never used once the printer is set up.

**Comment by Sunspark-007** [comment]
You are right, opening the dialog does make this link start working.

I am of two minds about what you said about the CUPS service.. on one hand you are right, why start a service if most people aren't going to be printing (which is true). On the other hand, I do believe in user experience polish where things should be consistent and not stick out like a nail.. so in this case, there is a start menu entry that takes the user to a "didn't work" webpage..

Maybe the solution to both is to somehow change the entry to "start service && rest of what's already there"?

**Comment by bertogg** [comment]
That wouldn't be a solution either because there are other ways to access the CUPS administration page.

If someone wants CUPS always on the solution is to run `systemctl enable cups.service`

**Comment by DJCrashdummy** [comment]
> The CUPS server is started on demand when someone tries to use the printing socket.

i understand and endorse this decision... especially for a highly optimized gaming first device.

> [...] the administration web page is almost never used once the printer is set up I don't think it's worth it.

also correct, but how should a printer be setup - by a noob - other than via the administration page? (...assuming he's using the default OS without installing much additional stuff.)

> I do believe in user experience polish where things should be consistent and not stick out like a nail.. so in this case, there is a start menu entry that takes the user to a "didn't work" webpage.

i fully agree with this! why add a start menu entry to a mostly not working "application"/program/service???
if you are savvy enough to (know how to) start the cups service manually, i'm pretty sure you are also savvy enough to access the administration page manually.
if you are not, and just stumble across the menu entry... it seems like printer support/administration is broken by default in SteamOS. 😦 

> If someone wants CUPS always on the solution is to run `systemctl enable cups.service`.

@bertogg IMHO nobody here is talking about permanently enabling the CUPS service... **but** about making the start menu entry work as expected and not let noobs (with no clue what a CUPS service is) assume that printer support is broken.

**so something like using `cupsctl && xdg-open http://localhost:631/` in the desktop-file instead of just `xdg-open http://localhost:631/` would be indeed a pretty easy fix!**

@Sunspark-007 it would be very kind if you can reopen this issue as i would be interested in the opinion of some Steam guys about this... so i don't have to create another one, as i strongly believe that this should be fixed.

**Comment by Sunspark-007** [comment]
I agree the suggestion is an easy polish that should be done, but I don't know that there's any point in re-opening.

**Comment by DJCrashdummy** [comment]
@Sunspark-007 the point of reopening is easy: if there is no ticket about that, hardly anyone (of the valve guys) will notice this issue and thus it is very unlikely that this will be addressed. thus, if there is an open ticket/discussion about it, chances are higher that his may get some attention sooner or later.
