### ISSUE TITLE
[Feature Request] Better UI for desktop.

### ISSUE THREAD

**Issue by BlakeBarnes00** [ValveSoftware/SteamOS#204]
I love the desktop already looks good, but could you add something that makes it look a bit "smoother" or "cleaner". It is a request you don't have to!

**Comment by ProfessorKaos64** [comment]
@BlakeBarnes00 , while it is great to tinkner and experiment  (I do this all the time with SteamOS-Tools), this really isn't going to change, as desktop mode is not the primary focus of SteamOS, and the OS itself is not designed around it.

**Comment by not83** [comment]
Agreed. Please close

**Comment by MrSchism** [comment]
Personally, I don't think closing is ready yet.  Having used my beta box for... well, a long time now... I've come to realize that changing to a different setup would probably free up some resources.  While it's not a big deal because Steam Machines should be beefier systems, it makes sense to move away from a heavy, full-tilt desktop environment, especially since it has to run in the background in some capacity.  I haven't tested, but based on performance, it seems Gnome 3 runs behind the SteamOS/BPM screen.

That's a LOT of overhead when you consider what's actually needed.

**Comment by not83** [comment]
Uhh what? How did you come to the conclusion that gnome is constantly
running in the background and/or heavy on resources?

**Comment by MrSchism** [comment]
Based on the fact that it drops to gnome desktop without having to launch it (from what I can tell).  It doesn't seem to load all of Gnome 3 (besides the window manager, which would already need to be loaded).

Gnome is heavy on resources compared to what little actually needs to be run: A window manager and maybe some desktop option.  I suggested Openbox/LXPanel with five items or so a few months ago.

**Comment by ProfessorKaos64** [comment]
Gnome3 does _not_ run from a standard system start. Verified over SSH:
```
desktop@steamos:~$ ps -aux | grep gnome-session
desktop    984  0.0  0.0  12960  2044 pts/0    S+   20:54   0:00 grep gnome-session
```
That line is only there because of the command issuing it of course.

**Comment by sharkwouter** [comment]
@MrSchism It actually only launches Gnome when you open the desktop for the first time after booting. Gnome just starts very fast. SteamOS runs nothing related to Gnome before that, SteamOS can work just fine without Gnome installed.

**Comment by MrGrymReaper** [comment]
@MrSchism - I too would like to see a better UI. Though more along the lines of it being a lightweight one (by default). Unless the more heavyweight one is installed for example GNOME or KDE.

An example of such a lightweight desktop could be LXDE (http://lxde.org/), XFCE (http://www.xfce.org/), LXQT (http://lxqt.org/). Alternatively an even more lightweight one such as Openbox (http://www.openbox.org/) or an equivalent.

Doing so would free up more resources for use by the SteamOS based devices. Improved performance experience of running games and other software. In addition to more resources hard disk and/or ram available for using the games or software installed on it.

Reduced need to restart because of running out of system resources (excluding when installing appropriate updates or software).

**Comment by sharkwouter** [comment]
If you want a different default desktop you can install a different one from the debian repo and set it as default with:

sudo dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.Accounts /org/freedesktop/Accounts/User1000 org.freedesktop.Accounts.User.SetXSession string:openbox

That would set openbox as default. You could also try switching with tasksel.

I don't see why you would, though. When using SteamOS from the Steam Big Picture mode, the only additional resources used are a couple of 100s of megabytes on the root partition(which should have 4 gigs free anyway). No other resources are used by Gnome unless you start it manually. If you log out after launching Gnome, it is killed and stops using any additional resources.

**Comment by MrGrymReaper** [comment]
@sharkwouter @MrSchism - It would ensure that there are less additional unwanted services (daemons) installed and/or running. These are programs which run in the background even when a user isn't logged in.

So even if the main programs which run while the user is logged are closed when they log out, these background processes will continue to run regardless.

Light weight desktop environments tend to have less of these types of programs which run automatically. In addition their coding is typically even more efficient than others; this is because they were originally developed to run on old or low specification devices.

**Comment by sharkwouter** [comment]
Can you list the unwanted daemons which are running?
