### ISSUE TITLE
Do not show not Linux games at SteamOS, and add actual FOSS games to the offer

### ISSUE THREAD

**Issue by mitcoes** [ValveSoftware/SteamOS#346]
I think Steam OS that already has more games than Xbox 360 and PS4 will be the console leader.

But not from GNU/Linux users, but from mainstream non techie gamers.

So it will be annoying for them to find non Linux titles, and i think it must be filtered by default the games you can buy or download for free.

And it will be great for them to be able to download FOSS Linux games as ioquake, or Tuxkart, or even better have some of them pre installed at their new consoles, so they will buy them with some fun inside.

**Comment by not83** [comment]
"So it will be annoying for them to find non Linux titles, and i think it
must be filtered by default the games you can buy or download for free"

At default install the store only shows SteamOS games or games you can
play.

Also it's up to the individual projects to add their games to steam.

Overall this isn't a big report really

**Comment by ProfessorKaos64** [comment]
What are you talking about @mitcoes ? While on SteamOS, unless you tick the options to show all games under Settings > Store, only Linux games are presented on the store. Furthermore, your library typically defaults (unless changed on last login) to SteamOS. You can easily add TuxKart as a non-steam game (I've done that myself), but if the game is not in the store, I don't believe it is a priority of Valve to implement a storefront or mechanism to add games from the Debian repositories, as they are not added as source lists by default, which is entirely intended. Some of the reason is damage control, you can't control how those non-Steam games will behave outside of the Steam runtime or steamcompmgr (compositor session). Add the Jessie sources appropriately, and add the non Steam game.

**Comment by johnv-valve** [comment]
I am closing this - the library view is already filtered by default.
Valve is not planning to ship any FOSS games.

**Comment by not83** [comment]
John who do we have to talk to in order to get some FOSS games onto steam?

**Comment by johnv-valve** [comment]
You need to go through Steam Greenlight to release a game on Steam.
http://steamcommunity.com/workshop/about/?appid=765&section=faq

**Comment by MrSchism** [comment]
Specifically, someone connected to the project directly (the primary maintainer, ideally) would have to go through greenlight.

**Comment by mitcoes** [comment]
Sorry to write so late. 

About the filter I was not writing about the library - It is filtered from the beginning - but about the shop.
If you search for games from a Linux client you will find MS WOS + MscOS + Linux games and not only Linux ones.

Also, there is no option to manage (or even only add with the +) Steam wine games from Steam Linux menu, that would be a good option for this cases.

I suppose future Steam Machines if it will be same day with some success on the market (perhaps with new cheap and good enough for 720p AAA gaming  AMD SoCs) will have zoom and or fonts or dpi settings, and of course Linux filters in the shop and or wine management, and also KODI, and some FOSS, even games, pre installed. Or not.
