### ISSUE TITLE
Output device switching to "echo-cancel-sink" and making it unable to change volume

### ISSUE THREAD

**Issue by CrazyCritic89** [ValveSoftware/SteamOS#822]
#### Your system information

* Steam client version: 1659369000
* SteamOS version: 20220803.1
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Sometimes when launching certain games, it'll switch the output device to "echo-cancel-sink" and make you unable to change volume and switch to headphones. It also seems only possible to fix by either restarting the client or system. Going into settings and trying to change it does nothing and only leaves "select a value" when you switch to other options. 
It also seems to happen in desktop mode sometimes as well, showing a box that it did, but it usually switches back a second after.

#### Steps for reproducing this issue:

It randomly happens when launching certain games it seems. The games that I've had this happen to me in are The Ultimate Doom (unverified) and Doom 2 (verified). I've also heard of it happening in GRIP (playable).

**Comment by AchillesPDX** [comment]
Same thing happening here. Seems related to putting the deck to sleep while playing a game, but I've yet to figure out exact steps to reproduce. Happening a LOT for me though.

**Comment by samworley** [comment]
Same thing happening to me occasionally

**Comment by Skoobie-Deux** [comment]
Happening to me, too. I'm often turning up the volume from Home Menu before starting the game in case I can't raise the volume in-game.

**Comment by nonlin** [comment]
Happens to be every time I launch fallout 4 and goes back to normal on exit.

**Comment by wbalson** [comment]
This is happening to me when I launch Fez through GOG (Lutris)

**Comment by TTimo** [comment]
Thank you, this is being worked on.

**Comment by dangerousdonut** [comment]
It may be a coincidence but Sonic & All-Stars Racing Transformed Collection is one of the games that I regularly encounter audio (loudness) issues with, and it will turn out to be related to (low) audio levels on echo-cancel sink.

**Comment by notimp** [comment]
Just a summery of weird audio stuff happening to me. (Everything on steamdeck.)

For me using steamlink audio (casting from the deck to the android app on an android tv box) glitched out, after I probably muted audio cancel sync and then unmuted it again in desktop mode - several days in between. 

So unmuting audio cancel sinc again at one point - then after that, I couldnt get audio out while steamlinking to an android device (under my tv) if in game mode. It would always work in desktop mode though. (About 20 reboots, same behavior.)

So I poked around a little. 

Enabled the other (emulated) HD audio device in audio thats listed there (for those reading along, you dont need to do that), then made it the default device, and deactevated he out of the box default device (maybe dont remember (50:50 that I did not) ) while having HD audio activated and set as the default audio device.
 
Then booted back to game mode.

Then hd audio would be the audio device in game mode. I noticed, because its max volume was much lower. But streaming audio over the steamlink device worked again.

So whatever settings you make in desktop mode in audio also propagate to game mode.
then switched back and forward (between game mode and desktop mode a bit). then had the bug reoccur, where echo cancel sink mutes everything in game mode, when streaming to the steamlink app on an android device.

Just from rebooting between modes and exiting and entering steamlink streaming via the android steamlink app a bunch.

So its not just the default audio devide thats effected.

Then went back to desktop mode, disabled the hd audio device again (you can do that from the small audio icon on the desktop, but the big enable button location is not where you get disable, instead its an option on the hd audio device itself).

And switched on the default audio device (maybe) and set it back to be the default audio device (certainly) again.

During that step I switched active audio devices a bunch, I noticed, that echo audio sync took over "focus" in desktop mode, but it didnt effect audio. so a popup popped that would periodically say it had taken over, but it hadnt (?).

Also swiching audio devices between echo audio sink and the default (factory default) audio device often glitched out (was indicated in the popup menu, but when I opened audio settings menu proper it hadnt changed there), or simply would refuse to (manually) change devices (radio buttons just not working).
 
Then at some pont it (audio cancel sink taking over) did mute every thing on desktop as well... which never happened prior. (Just from switching active states (between different audio devices.))

Regardless, as I knew that enabling HDaudio wasnt the fix, I disabled it again, that went through. then enabled the default audio device again (unsure), set it to default values, and as the default audio device (im certain of that part). rebooted to game mode, and suddenly audio streaming over steamlink to the android device had started working as well again (echosink still turned on, at default settings). 
which it wouldnt during 20 or so reboots earlier. (The initial issue.)

I left it at that.

ITS GLITCHED. as eff. 😉

Now everything (included shared audio in game mode while streaming to a steamlinked android box under my tv) works again. (otherwise shared audio would only work in desktop mode, not game mode during 20 reboots prior of me poking around in audio settings - always working in desktop mode, but not in game mode, btw -). 

But - now sometimes, in gamemode echo sink taking over game mode audio (muting it) intermittendly still happens, while steamlink sharing to the android box. usually after connecting and disconnecting steamlink a bunch.

That said, this now  (after the HDaudio and change default audio device intermission) gets fixed on reboot. :) Always. After one. :)

So I got everything working again to a reasonable state, but still glitchy, echo cancel sink randomly taking over in game mode and muting everything (only while streaming over steamlink its audio, so steamdecks audio (the speakers) itself never gets muted for me unintentionally in game mode) is a thing. So is desktop settings propagating to game mode.)

Have fun figuring that one out.. ;) But something is messed up primo - when echosink gets engaged, muted, or disabled, in combination with game mode audio sharing to external devices over steamlinl (havent tried a HDMI dock so far).

**Comment by AaronTank** [comment]
Having the same issue. I've seen it pop up when switching to/from desktop mode, and when changing accounts. Rebooting generally fixes the issue.

**Comment by jennichater** [comment]
Happening for me with Mass Effect Legendary Edition - every time i load into the game (Mass Effect 1 in this case) I can only change 'echo cancel sink' with the volume buttons. If I exit the game and change to desktop mode I can re-enable speakers again, but re-launching Mass Effect borks it again.

**Comment by Syragar** [comment]
It happens to me with several games. I noticed it happen with Mercenary Kings once or twice. It happens a lot with River City Girls.

**Comment by googlematt** [comment]
Experiencing this almost every time I use the deck now.  Workaround doesn't work anymore either (change audio device and then change it back to speakers).  So I have to restart just to change the volume.

FIND A SOLUTION

**Comment by TTimo** [comment]
This is fixed in the Preview channel.

**Comment by CrazyCritic89** [comment]
It seems this issue has been fixed for a while now, closing.

**Comment by akakira** [comment]
My device just started doing this today, I can boot to desktop and change echo sync to the speakers and get sound back, but when I go back to gaming mode I lose all sound.
