### ISSUE TITLE
File Manager Context Menu breaks when not selecting anything via touch input

### ISSUE THREAD

**Issue by Morpheus0x** [ValveSoftware/SteamOS#949]
#### Your system information

* Steam client version: 1671675017
* SteamOS version: 3.4.2 (also tested on beta 3.4.3)
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
In Desktop Mode, only using touchscreen, open the file manager(dolphin) and long press on any file or folder, don't select anything but instead click away. Long pressing again opening a context menu, but this time nothing can be clicked. The only way to fix this is to press Y or B which emulates keyboard keys r and d respectively. After that the file manager seems responsive again, however opening a context menu again results in the same freeze state. Only exiting dolphin and opening it again fixes it. Always selecting an option from the context menu without clicking away works as expected.

#### Steps for reproducing this issue:

1. Go to Desktop Mode
2. Open File Manager (Dolphin), only use touchscreen input from now on
3. Long press any folder or file to open context menu
4. Don't select anything from that menu and instead click away 
5. Long press again, now it's impossible click on anything in the file manager

**Comment by Pointedstick** [comment]
I can confirm this issue with the Dolphin file manager on the version shipping with the Steam Deck when run on X11. The issue does not appear when run on Wayland. Additionally, the press-and-hold UX has changed in the newer upstream KDE release that came out last month and includes Dolphin 22.12; Now pressing-and-holding enters a dedicated selection mode with contextual actions shown in a toolbar rather than a menu. I've tested that the bug no longer occurs with this newer version of Dolphin either on X11 or Wayland. So once SteamOS is updated to ship this newer Dolphin version, the problem will disappear.
